name: Code Check

on:
  workflow_call:

permissions:
  contents: read

env:
  SKIP: hadolint

jobs:
  pre-commit:
    name: Run pre-commit on repository
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: pre-commit/action@v3.0.0
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: failure() && github.event_name == 'pull_request'
      with:
        commit_message: "style: apply pre-commit changes"
    - uses: peter-evans/create-pull-request@v5
      if: failure() && github.event_name != 'pull_request'
      with:
        commit-message: "style: apply pre-commit changes"
  hadolint:
    name: Run hadolint on repository
    runs-on: ubuntu-latest
    needs:
      - pre-commit
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@v3
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        format: sarif
        output-file: hadolint.sarif
    - uses: github/codeql-action/upload-sarif@v2
      if: success() || failure()
      with:
        sarif_file: hadolint.sarif
        category: hadolint
  checkov:
    name: Run checkov on repository
    runs-on: ubuntu-latest
    needs:
      - pre-commit
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@v3
    - uses: bridgecrewio/checkov-action@v12
      with:
        output_format: cli,sarif
        output_file_path: console,checkov.sarif
    - uses: github/codeql-action/upload-sarif@v2
      if: success() || failure()
      with:
        sarif_file: checkov.sarif
        category: checkov
