name: Push

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

permissions:
  contents: read

jobs:
  commit-check:
    name: "Commit Check"
    uses: ./.github/workflows/commit-check.yaml
  code-check:
    name: "Code Check"
    needs:
      - commit-check
    permissions:
      contents: write
      pull-requests: write
      security-events: write
    uses: ./.github/workflows/code-check.yaml
  build:
    name: "Build"
    needs:
      - code-check
    permissions:
      contents: write
      packages: write
      security-events: write
    uses: ./.github/workflows/build.yaml
    with:
      publish: true
